Repository OWASP/ASVS, pull requests merged in 2019-02, with the labels that each got.

#406 Added CWEs to Malicious and API Segments. In Progress
  4.0/en/0x12-V3-Session-management.md
  4.0/en/0x12-V4-Access-Control.md
  4.0/en/0x19-V13-Malicious.md
  4.0/en/0x23-V18-API.md
Labels: enhancement

#437 Password length proposed change
  4.0/en/0x11-V2-Authentication.md
Labels: question

#462 Removed 3.1 export files.
  OWASP Application Security Verification Standard 3.1.docx
  OWASP Application Security Verification Standard 3.1.json
  OWASP Application Security Verification Standard 3.1.pdf
  OWASP Application Security Verification Standard 3.1.xlsx
Labels: QA, bug

#562 Update 0x12-V3-Session-management.md
  4.0/en/0x12-V3-Session-management.md
Labels: QA

#567 Clarify SSRF and move unvalidated redirect to input validation
  4.0/en/0x13-V5-Validation-Sanitization-Encoding.md
  4.0/en/0x20-V12-Files-Resources.md
Labels: QA

#596 Update 0x90-Appendix-A_Glossary.md
  4.0/en/0x90-Appendix-A_Glossary.md
Labels: QA

#597 Update 0x90-Appendix-A_Glossary.md
  4.0/en/0x90-Appendix-A_Glossary.md
Labels: QA

#600 Update 0x22-V14-Config.md
  4.0/en/0x22-V14-Config.md
Labels: QA

#601 Update 0x22-V14-Config.md
  4.0/en/0x22-V14-Config.md
Labels: QA

#602 Update 0x22-V14-Config.md
  4.0/en/0x22-V14-Config.md
Labels: QA

#603 Update 0x18-V10-Malicious.md
  4.0/en/0x18-V10-Malicious.md
Labels: QA

#604 Update 0x14-V6-Cryptography.md
  4.0/en/0x14-V6-Cryptography.md
Labels: QA

#605 Update 0x13-V5-Validation-Sanitization-Encoding.md
  4.0/en/0x13-V5-Validation-Sanitization-Encoding.md
Labels: QA

#606 Update 0x13-V5-Validation-Sanitization-Encoding.md
  4.0/en/0x13-V5-Validation-Sanitization-Encoding.md
Labels: QA

#607 Update 0x11-V2-Authentication.md
  4.0/en/0x11-V2-Authentication.md
Labels: QA

#608 Update 0x11-V2-Authentication.md
  4.0/en/0x11-V2-Authentication.md
Labels: QA

#609 Update 0x11-V2-Authentication.md
  4.0/en/0x11-V2-Authentication.md
Labels: QA
