Repository OWASP/ASVS, pull requests merged in 2022-05, with the labels that each got.

#1275 Fixing incorrect link in V3
  5.0/en/0x12-V3-Session-management.md
Labels: PR awaiting review, 5.0

#1267 remove 2.5.3 as duplicate of 2.4.1, closes #1134
  5.0/en/0x11-V2-Authentication.md
Labels: Awaiting response

#1263 Update 0x11-V2-Authentication.md
  5.0/en/0x11-V2-Authentication.md
Labels: Awaiting response

#1221 Starting to rework V9 Communications
  5.0/en/0x17-V9-Communications.md
Labels: PR awaiting review

#1258 Further modifications based on #1250
  5.0/en/0x13-V5-Validation-Sanitization-Encoding.md
Labels: PR awaiting review

#1259 Modify contribution guide
  CONTRIBUTING.md
Labels: PR awaiting review

#1279 Add reference to Clear-Site-Data header
  5.0/en/0x16-V8-Data-Protection.md
Labels: PR awaiting review, 5.0

#1269 Control 2.2.1
  5.0/en/0x11-V2-Authentication.md
Labels: PR awaiting review

#1282 Update README.md
  README.md
Labels: PR awaiting review

#1281 Resolve #1270
  5.0/en/0x22-V14-Config.md
Labels: PR awaiting review
