Repository OWASP/ASVS, pull requests merged in 2023-06, with the labels that each got.

#1641 Add new session revocation requirements as per #1417
  5.0/en/0x12-V3-Session-management.md
Labels: 6) PR awaiting review, 5.0 - prep

#1648 Delete 14.1.4 to resolve #1527
  5.0/en/0x22-V14-Config.md
Labels: 6) PR awaiting review, _5.0 - prep

#1646 Remove 4.1.2 to resolve #1524
  5.0/en/0x12-V4-Access-Control.md
Labels: 6) PR awaiting review, _5.0 - prep

#1647 Clarified wording of 7.4.2 to resolve #1379
  5.0/en/0x15-V7-Error-Logging.md
Labels: 6) PR awaiting review, _5.0 - prep

#1294 Owasp makefile
  .gitignore
  4.0/cre_mapping_table.md
  4.0/generate-all.sh
  4.0/install_deps.sh
  4.0/tools/asvs.py
  4.0/tools/export.py
  4.0/tools/requirements.txt
  5.0/Makefile
  5.0/en/0x00-Header.yaml
  5.0/en/0x01-Header.yaml
  5.0/generate-all.sh
  5.0/templates/eisvogel.tex
  5.0/templates/header-eisvogel.tex
  5.0/tools/asvs.py
  Makefile
  docker/Dockerfile
  docker/run.sh
Labels: 2) Awaiting response, _5.0 - Not blocker

#1669 Add 5.2.9 for sanitizing regexes to resolve #1600
  5.0/en/0x13-V5-Validation-Sanitization-Encoding.md
Labels: 6) PR awaiting review, _5.0 - prep
